import './globals.css'
import { Lustria, Lato } from 'next/font/google'

const lustria = Lustria({
  subsets: ['latin'],
  variable: '--font-lustria',
  display: 'swap',
  weight: ['400']
})
const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  display: 'swap',
  weight: ['400', '700']
}) 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lustria.variable} ${lato.variable}`}>{children}</body>
    </html>
  )
}
